# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
    Build:
      name: ${{ matrix.name }} w/ Python ${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          python-version: ["3.9"]
          include:
            - os: ubuntu-latest
              name: Linux
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

        
      - name: Dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Test
      #   run: |
      #     echo "done" | python examples/mechanism_synthesis.py

      - name: pytest
        run: |
          pip install pytest
          pytest -v --tb=short
      
      # - name: Test Beta Implicit Diff Example
      #   run: |
      #     python tests/test_beta_implicit_diff.py
